package resources;

public class TestDataBuild {

	public String notoficationRegistrationSmsPayload(String phoneNo) {
		return "{\r\n" + "    \"sms-for\":\"Successfully Registered\",\r\n" + "    \"mobileNumber\":\"" + phoneNo
				+ "\",\r\n" + "    \"data\":{\r\n" + "        \"userEmail\":\"dddda\",\r\n"
				+ "        \"phoneNumber\":\"" + phoneNo + "\"\r\n" + "    }\r\n" + "}";
	}

	public String notificationEmailPayload(String email) {
		return "{\r\n" + " \"emailTemplateType\": \"CART\",\r\n" + " \"to\": \"" + email + "\",\r\n" + " \"cc\": \""
				+ email + "\",\r\n" + " \"subject\": \"Your cart is ready for payment\",\r\n"
				+ " \"template\": \"ENQUIRY_CUSTOMER_SINGLE\",\r\n" + " \"orderSummaryData\": {\r\n"
				+ " \"identifier\": {\r\n" + " \"type\": \"CART\",\r\n"
				+ " \"id\": \"cae21eba-7fa6-4f27-8a9b-86ace193cc2c\",\r\n" + " \"category\": \"DISTRIBUTED\",\r\n"
				+ " \"version\": 27\r\n" + " },\r\n" + " \"orderNumber\": null,\r\n"
				+ " \"orderDate\": \"10 Nov 2022\",\r\n" + " \"orderPaymentStatus\": null,\r\n"
				+ " \"customerData\": {\r\n" + " \"customerId\": \"feb5a3bd-b11e-45aa-b138-ff35d48108b6\",\r\n"
				+ " \"name\": \"Ankit Kumar\",\r\n" + " \"email\": \"ankit.kumar3@jsw.in\",\r\n"
				+ " \"phoneNumber\": \"8340429435\",\r\n"
				+ " \"companyName\": \"ODISHA CONSUMERS CO OPERATIVE FEDERATION LIMITED\",\r\n"
				+ " \"gstIn\": \"21AAAAO0683L1ZO\",\r\n" + " \"beneficiaryName\": \"JSW ONE PLATFORMS LIMITED\",\r\n"
				+ " \"beneficiaryAccountNum\": \"ba_KPieID06fE81g3\",\r\n" + " \"ifscCode\": \"RAZR0000001\",\r\n"
				+ " \"customerVAN\": \"1112220097609923\",\r\n" + " \"virtualAccountId\": \"va_KPieI0VYUXTaAm\",\r\n"
				+ " \"salesClassification\": \"nonsuccess\",\r\n" + " \"bankName\": \"RBL Bank\",\r\n"
				+ " \"testUser\": false\r\n" + " },\r\n" + " \"orderStatus\": null,\r\n"
				+ " \"totalOrderAmount\": {\r\n" + " \"centAmount\": 312766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"shippingMode\": \"Delivery\",\r\n" + " \"appliedDiscounts\": [],\r\n"
				+ " \"appliedDiscountsV2\": [],\r\n" + " \"shippingAddress\": {\r\n" + " \"id\": \"LHIi4otj\",\r\n"
				+ " \"streetLine\": \"HOLDING NO-2934 WARD NO-10\",\r\n" + " \"postalCode\": \"751001\",\r\n"
				+ " \"city\": \"BHUBANESWAR\",\r\n" + " \"region\": \"KHORDHA\",\r\n" + " \"state\": \"ODISHA\",\r\n"
				+ " \"company\": null,\r\n" + " \"mobile\": null\r\n" + " },\r\n" + " \"billingAddress\": {\r\n"
				+ " \"id\": \"LHIi4otj\",\r\n" + " \"streetLine\": \"HOLDING NO-2934 WARD NO-10\",\r\n"
				+ " \"postalCode\": \"751001\",\r\n" + " \"city\": \"BHUBANESWAR\",\r\n"
				+ " \"region\": \"KHORDHA\",\r\n" + " \"state\": \"ODISHA\",\r\n" + " \"company\": null,\r\n"
				+ " \"mobile\": null\r\n" + " },\r\n" + " \"distributorAddresses\": [\r\n" + " {\r\n"
				+ " \"id\": \"q-FxNdYn\",\r\n" + " \"streetLine\": \"1/176, \",\r\n"
				+ " \"postalCode\": \"410501\",\r\n" + " \"city\": \"Pune\",\r\n" + " \"region\": \"Maharashtra\",\r\n"
				+ " \"state\": \"Tamil Nadu\",\r\n" + " \"company\": \"Bhanu Enterprise\",\r\n"
				+ " \"mobile\": \"6362261134\"\r\n" + " },\r\n" + " {\r\n" + " \"id\": \"q-FxNdYn\",\r\n"
				+ " \"streetLine\": \"1/176, \",\r\n" + " \"postalCode\": \"410501\",\r\n" + " \"city\": \"Pune\",\r\n"
				+ " \"region\": \"Maharashtra\",\r\n" + " \"state\": \"Tamil Nadu\",\r\n"
				+ " \"company\": \"Bhanu Enterprise\",\r\n" + " \"mobile\": \"6362261134\"\r\n" + " }\r\n" + " ],\r\n"
				+ " \"totalQuantityDelivered\": null,\r\n" + " \"totalReadyForDispatch\": null,\r\n"
				+ " \"totalQuantity\": null,\r\n" + " \"totalRemainingToBeDelivered\": null,\r\n"
				+ " \"totalPaymentReceived\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " },\r\n"
				+ " \"totalAmountOutstanding\": {\r\n" + " \"centAmount\": 312766074,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"35,27,660.74\",\r\n"
				+ " \"absoluteDisplayAmount\": \"35,27,660\",\r\n" + " \"precisionAmount\": 352766074000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"paymentSummaryList\": [\r\n" + " {\r\n"
				+ " \"identifier\": {\r\n" + " \"type\": \"CART\",\r\n"
				+ " \"id\": \"cae21eba-7fa6-4f27-8a9b-86ace193cc2c\",\r\n"
				+ " \"plantName\": \"Test Steel Agencies\",\r\n" + " \"category\": \"DISTRIBUTED\",\r\n"
				+ " \"key\": null\r\n" + " },\r\n" + " \"totalLineItemPrice\": {\r\n"
				+ " \"centAmount\": 294992200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"29,49,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"29,49,922\",\r\n"
				+ " \"precisionAmount\": 294992200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"totalDiscountedLineItemPrice\": {\r\n" + " \"centAmount\": 294992200,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"29,49,922.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"29,49,922\",\r\n" + " \"precisionAmount\": 294992200000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"totalLineItemTax\": {\r\n"
				+ " \"centAmount\": 53098596,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"5,30,985.96\",\r\n" + " \"absoluteDisplayAmount\": \"5,30,985\",\r\n"
				+ " \"precisionAmount\": 53098596000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"totalOrderAmount\": {\r\n" + " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"totalPrice\": {\r\n" + " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"totalReceivedAmount\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " },\r\n" + " \"totalDueAmount\": {\r\n"
				+ " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"totalRequestedAmount\": {\r\n" + " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"netAdvancePayable\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " },\r\n"
				+ " \"paymentBeforeDelivery\": {\r\n" + " \"centAmount\": 352766074,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"35,27,660.74\",\r\n"
				+ " \"absoluteDisplayAmount\": \"35,27,660\",\r\n" + " \"precisionAmount\": 352766074000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"discounts\": {\r\n" + " \"sellerDiscount\": {\r\n"
				+ " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n"
				+ " },\r\n" + " \"platformDiscount\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " }\r\n" + " },\r\n"
				+ " \"adjustments\": {\r\n" + " \"advance\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": null,\r\n" + " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " },\r\n" + " \"credit\": {\r\n"
				+ " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n"
				+ " },\r\n" + " \"tolerance\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " }\r\n" + " },\r\n"
				+ " \"charges\": {\r\n" + " \"delivery\": {\r\n" + " \"centAmount\": 4675278,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"46,752.78\",\r\n"
				+ " \"absoluteDisplayAmount\": \"46,752\",\r\n" + " \"precisionAmount\": 4675278000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"other\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": null,\r\n" + " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " },\r\n"
				+ " \"discountedDelivery\": {\r\n" + " \"centAmount\": 4675278,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"46,752.78\",\r\n" + " \"absoluteDisplayAmount\": \"46,752\",\r\n"
				+ " \"precisionAmount\": 4675278000,\r\n" + " \"precision\": 5\r\n" + " }\r\n" + " },\r\n"
				+ " \"paymentAwaited\": {\r\n" + " \"id\": \"d06f2a37-e194-47aa-a2c5-a1cfaa385aa1\",\r\n"
				+ " \"type\": \"FINAL\",\r\n" + " \"version\": 2,\r\n" + " \"amount\": {\r\n"
				+ " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"state\": \"INITIAL\",\r\n" + " \"paymentMethod\": null,\r\n" + " \"paymentInterface\": null,\r\n"
				+ " \"transactions\": [],\r\n" + " \"paymentLink\": null\r\n" + " },\r\n"
				+ " \"lastSuccessfulPayment\": null,\r\n" + " \"lastConfirmedPayment\": null,\r\n"
				+ " \"payments\": [\r\n" + " {\r\n" + " \"id\": \"d06f2a37-e194-47aa-a2c5-a1cfaa385aa1\",\r\n"
				+ " \"type\": \"FINAL\",\r\n" + " \"version\": 2,\r\n" + " \"amount\": {\r\n"
				+ " \"centAmount\": 352766074,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"35,27,660.74\",\r\n" + " \"absoluteDisplayAmount\": \"35,27,660\",\r\n"
				+ " \"precisionAmount\": 352766074000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"state\": \"INITIAL\",\r\n" + " \"paymentMethod\": null,\r\n" + " \"paymentInterface\": null,\r\n"
				+ " \"transactions\": [],\r\n" + " \"paymentLink\": \"https://qa-ssr.msme.jswone.in/payment\"\r\n"
				+ " }\r\n" + " ],\r\n" + " \"associatedSkus\": [\r\n"
				+ " \"JSW Pragati+ Pre-Painted Galvalume Coils IS 15965:2012 YS550 - 0.5 - 1250 - 150 - Sky Blue\",\r\n"
				+ " \"Hot Rolled Sheets IS 2062:2011 E250BR - 2 - 900 - 2500\"\r\n" + " ]\r\n" + " }\r\n" + " ],\r\n"
				+ " \"lineItemList\": [\r\n" + " {\r\n" + " \"lineItemIdentifier\": {\r\n"
				+ " \"ctLineItemId\": \"51f8ed6b-0018-4f55-9071-451eb95c6e7e\",\r\n" + " \"sapLineItemId\": \"10\"\r\n"
				+ " },\r\n" + " \"productSlug\": \"JSW_Pragati-15965_2012-ys_550-01\",\r\n"
				+ " \"productForm\": \"PPGLCF\",\r\n" + " \"variantId\": 14,\r\n"
				+ " \"variantKey\": \"JSW_Pragati-PPGLCF-15965_2012-YS_550-0.5-1250-150-Sky_Blue\",\r\n"
				+ " \"sku\": \"JSW Pragati+ Pre-Painted Galvalume Coils IS 15965:2012 YS550 - 0.5 - 1250 - 150 - Sky Blue\",\r\n"
				+ " \"imageUrl\": \"//images.ctfassets.net/o0otttl8ele8/1h1SyMftavoq6dDFEv6kRj/804dbfb58acb384c2666bc49bfc3a7a9/colour_coated_prod.jpeg\",\r\n"
				+ " \"name\": \"JSW Pragati+ Pre-Painted Galvalume Coils IS 15965:2012 YS550\",\r\n"
				+ " \"sellerName\": \"Test Steel Authority\",\r\n" + " \"sellerKey\": \"TSA\",\r\n"
				+ " \"attributes\": {\r\n" + " \"Thickness\": \"0.5 mm\",\r\n" + " \"Width\": \"1250 mm\",\r\n"
				+ " \"Colour\": \"Sky_Blue-#87ceeb\",\r\n" + " \"Coating grade (AZ)\": \"150 GSM\"\r\n" + " },\r\n"
				+ " \"deliveryStatus\": [\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_DELIVERED\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_READY_FOR_PICKUP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_DISPATCH_READY\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_PICKED_UP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DELIVERED\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_CONFIRMED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DISPATCH\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"CONFIRMED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n"
				+ " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_APPROVED_FOR_DISPATCH\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"PLACED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n"
				+ " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_DISPATCHED\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_APPROVED_FOR_PICKUP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_STOCK_READY\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " }\r\n" + " ],\r\n"
				+ " \"quantity\": {\r\n" + " \"primaryQuantity\": \"23 MT\",\r\n" + " \"secondaryQuantity\": null,\r\n"
				+ " \"primaryUom\": {\r\n" + " \"unit\": \"MT\",\r\n" + " \"value\": 23.0,\r\n"
				+ " \"label\": \"MT\",\r\n" + " \"priceLabel\": \"MT\"\r\n" + " },\r\n" + " \"ctUom\": {\r\n"
				+ " \"unit\": \"KG\",\r\n" + " \"value\": 23000,\r\n" + " \"label\": \"KG\",\r\n"
				+ " \"priceLabel\": null\r\n" + " },\r\n" + " \"secondaryUom\": null\r\n" + " },\r\n"
				+ " \"totalQuantityReadyForDispatch\": {\r\n" + " \"primaryQuantity\": null,\r\n"
				+ " \"secondaryQuantity\": null,\r\n" + " \"primaryUom\": null,\r\n" + " \"ctUom\": null,\r\n"
				+ " \"secondaryUom\": null\r\n" + " },\r\n" + " \"payableAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"ctAttributes\": {\r\n" + " \"THICKNESS_MM\": \"0.5 mm\",\r\n"
				+ " \"WIDTH_MM\": \"1250 mm\",\r\n" + " \"S_COLOUR_CODE_TOP\": \"Sky_Blue-#87ceeb\",\r\n"
				+ " \"S_AL_ZN_COATING_GSM_MIN\": \"150 GSM\"\r\n" + " },\r\n" + " \"availableQuantity\": {\r\n"
				+ " \"primaryQuantity\": null,\r\n" + " \"secondaryQuantity\": null,\r\n" + " \"primaryUom\": {\r\n"
				+ " \"unit\": \"MT\",\r\n" + " \"value\": 29.0,\r\n" + " \"label\": \"MT\",\r\n"
				+ " \"priceLabel\": \"MT\"\r\n" + " },\r\n" + " \"ctUom\": {\r\n" + " \"unit\": \"KG\",\r\n"
				+ " \"value\": 29000,\r\n" + " \"label\": \"KG\",\r\n" + " \"priceLabel\": null\r\n" + " },\r\n"
				+ " \"secondaryUom\": null\r\n" + " },\r\n" + " \"freightInclusivePrice\": false,\r\n"
				+ " \"brand\": \"JSW Steel\",\r\n" + " \"channelName\": \"Test Steel Agencies\",\r\n"
				+ " \"channelKey\": \"TSA\",\r\n" + " \"channelAddress\": {\r\n"
				+ " \"id\": \"c9f608fa-0f62-40a9-b328-6a21a986180a\",\r\n" + " \"streetLine\": \"520 Test\",\r\n"
				+ " \"postalCode\": \"600040\",\r\n" + " \"city\": \"Chennai\",\r\n" + " \"region\": \"Chennai\",\r\n"
				+ " \"state\": \"Tamil Nadu\",\r\n" + " \"company\": null,\r\n" + " \"mobile\": null\r\n" + " },\r\n"
				+ " \"productType\": \"Steel PPGL Coil\",\r\n" + " \"grade\": \"15965_2012\",\r\n"
				+ " \"subGrade\": \"YS_550\",\r\n" + " \"lineItemTaxRatio\": 0.18,\r\n" + " \"lineItemAmount\": {\r\n"
				+ " \"centAmount\": 158700000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"15,87,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"15,87,000\",\r\n"
				+ " \"precisionAmount\": 158700000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"lineItemTaxedAmount\": {\r\n" + " \"centAmount\": 187266000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"18,72,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"18,72,660\",\r\n"
				+ " \"precisionAmount\": 187266000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"lineItemAmounts\": {\r\n" + " \"payableAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"amount\": {\r\n" + " \"centAmount\": 158700000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"15,87,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"15,87,000\",\r\n"
				+ " \"precisionAmount\": 158700000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxedAmount\": {\r\n" + " \"centAmount\": 187266000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"18,72,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"18,72,660\",\r\n"
				+ " \"precisionAmount\": 187266000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedAmount\": {\r\n" + " \"centAmount\": 158700000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"15,87,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"15,87,000\",\r\n"
				+ " \"precisionAmount\": 158700000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedTaxedAmount\": {\r\n" + " \"centAmount\": 187266000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"18,72,660.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"18,72,660\",\r\n" + " \"precisionAmount\": 187266000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"perUnitAmount\": {\r\n" + " \"centAmount\": 6900000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"69,000.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"69,000\",\r\n" + " \"precisionAmount\": 6900000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"discountedPerUnitAmount\": {\r\n"
				+ " \"centAmount\": 6900000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"69,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"69,000\",\r\n"
				+ " \"precisionAmount\": 6900000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"previousPerUnitAmount\": {\r\n" + " \"centAmount\": 6900000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"69,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"69,000\",\r\n"
				+ " \"precisionAmount\": 6900000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedTaxAmount\": null,\r\n" + " \"lineItemTaxAmount\": null\r\n" + " },\r\n"
				+ " \"lineItemAmountsV2\": {\r\n" + " \"payableAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"amount\": {\r\n" + " \"centAmount\": 158700000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"15,87,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"15,87,000\",\r\n"
				+ " \"precisionAmount\": 158700000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedAmount\": {\r\n" + " \"centAmount\": 158700000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"15,87,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"15,87,000\",\r\n"
				+ " \"precisionAmount\": 158700000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"perUnitAmount\": {\r\n" + " \"centAmount\": 6900000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"69,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"69,000\",\r\n"
				+ " \"precisionAmount\": 6900000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"perUnitAmountTax\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 1242000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"12,420.00\",\r\n" + " \"absoluteDisplayAmount\": \"12,420\",\r\n"
				+ " \"precisionAmount\": 1242000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 1242000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"12,420.00\",\r\n" + " \"absoluteDisplayAmount\": \"12,420\",\r\n"
				+ " \"precisionAmount\": 1242000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"discountedPerUnitAmount\": {\r\n" + " \"centAmount\": 6900000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"69,000.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"69,000\",\r\n" + " \"precisionAmount\": 6900000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"discountedPerUnitAmountTax\": {\r\n"
				+ " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n" + " \"centAmount\": 1242000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"12,420.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"12,420\",\r\n" + " \"precisionAmount\": 1242000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n" + " {\r\n" + " \"taxAmount\": {\r\n"
				+ " \"centAmount\": 1242000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"12,420.00\",\r\n" + " \"absoluteDisplayAmount\": \"12,420\",\r\n"
				+ " \"precisionAmount\": 1242000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"previousPerUnitAmount\": {\r\n" + " \"centAmount\": 6900000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"69,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"69,000\",\r\n"
				+ " \"precisionAmount\": 6900000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxOnDiscountAmount\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 28566000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,85,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"2,85,660\",\r\n"
				+ " \"precisionAmount\": 28566000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 28566000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,85,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"2,85,660\",\r\n"
				+ " \"precisionAmount\": 28566000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"taxOnlineItemAmount\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 28566000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,85,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"2,85,660\",\r\n"
				+ " \"precisionAmount\": 28566000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 28566000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,85,660.00\",\r\n" + " \"absoluteDisplayAmount\": \"2,85,660\",\r\n"
				+ " \"precisionAmount\": 28566000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"partingCharge\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"partingChargeTax\": {\r\n"
				+ " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"taxList\": [\r\n" + " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n"
				+ " },\r\n" + " \"bendingCharge\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " }\r\n" + " }\r\n" + " },\r\n" + " {\r\n"
				+ " \"lineItemIdentifier\": {\r\n" + " \"ctLineItemId\": \"e34fb644-359e-4756-a948-ba01dd01c77e\",\r\n"
				+ " \"sapLineItemId\": \"10\"\r\n" + " },\r\n" + " \"productSlug\": \"2062_2011-e250br-02\",\r\n"
				+ " \"productForm\": \"HRCTLF\",\r\n" + " \"variantId\": 2,\r\n"
				+ " \"variantKey\": \"HRCTLF-2062_2011-E250BR-2-900-2500\",\r\n"
				+ " \"sku\": \"Hot Rolled Sheets IS 2062:2011 E250BR - 2 - 900 - 2500\",\r\n"
				+ " \"imageUrl\": \"//images.ctfassets.net/o0otttl8ele8/uybdfpXojK0HzeFIhZb3T/0180291f86e3b9ef80c0a7ef10be96f7/shutterstock_391558495.jpg\",\r\n"
				+ " \"name\": \"JSW Steel Hot Rolled Sheets IS 2062:2011 E250BR\",\r\n"
				+ " \"sellerName\": \"Test Steel Agencies\",\r\n" + " \"sellerKey\": \"TSA\",\r\n"
				+ " \"attributes\": {\r\n" + " \"Thickness\": \"2 mm\",\r\n" + " \"Width (mm)\": \"900 mm\",\r\n"
				+ " \"Length\": \"2500 mm\"\r\n" + " },\r\n" + " \"deliveryStatus\": [\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_DELIVERED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_READY_FOR_PICKUP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_DISPATCH_READY\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_PICKED_UP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DELIVERED\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_CONFIRMED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DISPATCH\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"CONFIRMED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n"
				+ " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_APPROVED_FOR_DISPATCH\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"PLACED\",\r\n" + " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n"
				+ " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_DISPATCHED\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " },\r\n" + " {\r\n"
				+ " \"state\": \"DIRECT_ORDER_APPROVED_FOR_PICKUP\",\r\n" + " \"stage\": \"COMPLETE\",\r\n"
				+ " \"quantity\": null\r\n" + " },\r\n" + " {\r\n" + " \"state\": \"DIRECT_ORDER_STOCK_READY\",\r\n"
				+ " \"stage\": \"COMPLETE\",\r\n" + " \"quantity\": null\r\n" + " }\r\n" + " ],\r\n"
				+ " \"quantity\": {\r\n" + " \"primaryQuantity\": \"16.621 MT\",\r\n"
				+ " \"secondaryQuantity\": \"456 sheets\",\r\n" + " \"primaryUom\": {\r\n" + " \"unit\": \"MT\",\r\n"
				+ " \"value\": 16.621,\r\n" + " \"label\": \"MT\",\r\n" + " \"priceLabel\": \"MT\"\r\n" + " },\r\n"
				+ " \"ctUom\": {\r\n" + " \"unit\": \"KG\",\r\n" + " \"value\": 16621,\r\n" + " \"label\": \"KG\",\r\n"
				+ " \"priceLabel\": null\r\n" + " },\r\n" + " \"secondaryUom\": {\r\n"
				+ " \"unit\": \"NUMBER_OF_SHEETS\",\r\n" + " \"value\": 455.9945,\r\n" + " \"label\": \"sheets\",\r\n"
				+ " \"priceLabel\": null\r\n" + " }\r\n" + " },\r\n" + " \"totalQuantityReadyForDispatch\": {\r\n"
				+ " \"primaryQuantity\": null,\r\n" + " \"secondaryQuantity\": null,\r\n" + " \"primaryUom\": null,\r\n"
				+ " \"ctUom\": null,\r\n" + " \"secondaryUom\": null\r\n" + " },\r\n" + " \"payableAmount\": {\r\n"
				+ " \"centAmount\": 0,\r\n" + " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"ctAttributes\": {\r\n" + " \"THICKNESS_MM\": \"2 mm\",\r\n"
				+ " \"WIDTH_MM\": \"900 mm\",\r\n" + " \"LENGTH_MM\": \"2500 mm\"\r\n" + " },\r\n"
				+ " \"availableQuantity\": {\r\n" + " \"primaryQuantity\": null,\r\n"
				+ " \"secondaryQuantity\": null,\r\n" + " \"primaryUom\": {\r\n" + " \"unit\": \"MT\",\r\n"
				+ " \"value\": 19.5,\r\n" + " \"label\": \"MT\",\r\n" + " \"priceLabel\": \"MT\"\r\n" + " },\r\n"
				+ " \"ctUom\": {\r\n" + " \"unit\": \"KG\",\r\n" + " \"value\": 19500,\r\n" + " \"label\": \"KG\",\r\n"
				+ " \"priceLabel\": null\r\n" + " },\r\n" + " \"secondaryUom\": {\r\n"
				+ " \"unit\": \"NUMBER_OF_SHEETS\",\r\n" + " \"value\": 535.0,\r\n" + " \"label\": \"sheets\",\r\n"
				+ " \"priceLabel\": null\r\n" + " }\r\n" + " },\r\n" + " \"freightInclusivePrice\": false,\r\n"
				+ " \"brand\": \"JSW Steel\",\r\n" + " \"channelName\": \"Test Steel Agencies\",\r\n"
				+ " \"channelKey\": \"TSA\",\r\n" + " \"channelAddress\": {\r\n"
				+ " \"id\": \"c9f608fa-0f62-40a9-b328-6a21a986180a\",\r\n" + " \"streetLine\": \"520 Test\",\r\n"
				+ " \"postalCode\": \"600040\",\r\n" + " \"city\": \"Chennai\",\r\n" + " \"region\": \"Chennai\",\r\n"
				+ " \"state\": \"Tamil Nadu\",\r\n" + " \"company\": null,\r\n" + " \"mobile\": null\r\n" + " },\r\n"
				+ " \"productType\": \"Steel HR Sheets\",\r\n" + " \"grade\": \"2062:2011\",\r\n"
				+ " \"subGrade\": \"E250BR\",\r\n" + " \"lineItemTaxRatio\": 0.18,\r\n" + " \"lineItemAmount\": {\r\n"
				+ " \"centAmount\": 136292200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"13,62,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"13,62,922\",\r\n"
				+ " \"precisionAmount\": 136292200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"lineItemTaxedAmount\": {\r\n" + " \"centAmount\": 160824796,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"16,08,247.96\",\r\n" + " \"absoluteDisplayAmount\": \"16,08,247\",\r\n"
				+ " \"precisionAmount\": 160824796000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"lineItemAmounts\": {\r\n" + " \"payableAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"amount\": {\r\n" + " \"centAmount\": 136292200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"13,62,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"13,62,922\",\r\n"
				+ " \"precisionAmount\": 136292200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxedAmount\": {\r\n" + " \"centAmount\": 160824796,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"16,08,247.96\",\r\n" + " \"absoluteDisplayAmount\": \"16,08,247\",\r\n"
				+ " \"precisionAmount\": 160824796000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedAmount\": {\r\n" + " \"centAmount\": 136292200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"13,62,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"13,62,922\",\r\n"
				+ " \"precisionAmount\": 136292200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedTaxedAmount\": {\r\n" + " \"centAmount\": 160824796,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"16,08,247.96\",\r\n"
				+ " \"absoluteDisplayAmount\": \"16,08,247\",\r\n" + " \"precisionAmount\": 160824796000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"perUnitAmount\": {\r\n" + " \"centAmount\": 8200000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"82,000.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"82,000\",\r\n" + " \"precisionAmount\": 8200000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"discountedPerUnitAmount\": {\r\n"
				+ " \"centAmount\": 8200000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"82,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"82,000\",\r\n"
				+ " \"precisionAmount\": 8200000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"previousPerUnitAmount\": {\r\n" + " \"centAmount\": 8200000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"82,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"82,000\",\r\n"
				+ " \"precisionAmount\": 8200000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedTaxAmount\": null,\r\n" + " \"lineItemTaxAmount\": null\r\n" + " },\r\n"
				+ " \"lineItemAmountsV2\": {\r\n" + " \"payableAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"amount\": {\r\n" + " \"centAmount\": 136292200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"13,62,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"13,62,922\",\r\n"
				+ " \"precisionAmount\": 136292200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"discountedAmount\": {\r\n" + " \"centAmount\": 136292200,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"13,62,922.00\",\r\n" + " \"absoluteDisplayAmount\": \"13,62,922\",\r\n"
				+ " \"precisionAmount\": 136292200000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"perUnitAmount\": {\r\n" + " \"centAmount\": 8200000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"82,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"82,000\",\r\n"
				+ " \"precisionAmount\": 8200000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"perUnitAmountTax\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 1476000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"14,760.00\",\r\n" + " \"absoluteDisplayAmount\": \"14,760\",\r\n"
				+ " \"precisionAmount\": 1476000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 1476000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"14,760.00\",\r\n" + " \"absoluteDisplayAmount\": \"14,760\",\r\n"
				+ " \"precisionAmount\": 1476000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"discountedPerUnitAmount\": {\r\n" + " \"centAmount\": 8200000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"82,000.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"82,000\",\r\n" + " \"precisionAmount\": 8200000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"discountedPerUnitAmountTax\": {\r\n"
				+ " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n" + " \"centAmount\": 1476000,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": \"14,760.00\",\r\n"
				+ " \"absoluteDisplayAmount\": \"14,760\",\r\n" + " \"precisionAmount\": 1476000000,\r\n"
				+ " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n" + " {\r\n" + " \"taxAmount\": {\r\n"
				+ " \"centAmount\": 1476000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"14,760.00\",\r\n" + " \"absoluteDisplayAmount\": \"14,760\",\r\n"
				+ " \"precisionAmount\": 1476000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"previousPerUnitAmount\": {\r\n" + " \"centAmount\": 8200000,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"82,000.00\",\r\n" + " \"absoluteDisplayAmount\": \"82,000\",\r\n"
				+ " \"precisionAmount\": 8200000000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxOnDiscountAmount\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 24532596,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,45,325.96\",\r\n" + " \"absoluteDisplayAmount\": \"2,45,325\",\r\n"
				+ " \"precisionAmount\": 24532596000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 24532596,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,45,325.96\",\r\n" + " \"absoluteDisplayAmount\": \"2,45,325\",\r\n"
				+ " \"precisionAmount\": 24532596000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"taxOnlineItemAmount\": {\r\n" + " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n"
				+ " \"centAmount\": 24532596,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,45,325.96\",\r\n" + " \"absoluteDisplayAmount\": \"2,45,325\",\r\n"
				+ " \"precisionAmount\": 24532596000,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"taxList\": [\r\n"
				+ " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 24532596,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": \"2,45,325.96\",\r\n" + " \"absoluteDisplayAmount\": \"2,45,325\",\r\n"
				+ " \"precisionAmount\": 24532596000,\r\n" + " \"precision\": 5\r\n" + " },\r\n"
				+ " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n" + " },\r\n"
				+ " \"partingCharge\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": \"INR\",\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n" + " },\r\n" + " \"partingChargeTax\": {\r\n"
				+ " \"totalTaxRatio\": 0.18,\r\n" + " \"totalTaxAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"taxList\": [\r\n" + " {\r\n" + " \"taxAmount\": {\r\n" + " \"centAmount\": 0,\r\n"
				+ " \"currency\": \"INR\",\r\n" + " \"displayAmount\": null,\r\n"
				+ " \"absoluteDisplayAmount\": null,\r\n" + " \"precisionAmount\": 0,\r\n" + " \"precision\": 5\r\n"
				+ " },\r\n" + " \"taxType\": \"IGST\",\r\n" + " \"taxRatio\": 0.18\r\n" + " }\r\n" + " ]\r\n"
				+ " },\r\n" + " \"bendingCharge\": {\r\n" + " \"centAmount\": 0,\r\n" + " \"currency\": null,\r\n"
				+ " \"displayAmount\": null,\r\n" + " \"absoluteDisplayAmount\": null,\r\n"
				+ " \"precisionAmount\": 0,\r\n" + " \"precision\": 0\r\n" + " }\r\n" + " }\r\n" + " }\r\n" + " ],\r\n"
				+ " \"summaryLink\": \"https://qa-ssr.msme.jswone.in/cart-detail\",\r\n" + " \"shipments\": [],\r\n"
				+ " \"sapInfo\": {\r\n" + " \"contractNumber\": null,\r\n" + " \"contractCreationDate\": null,\r\n"
				+ " \"sapMetadata\": null,\r\n" + " \"orderCreationDate\": null,\r\n" + " \"validStartDate\": null,\r\n"
				+ " \"validEndDate\": null\r\n" + " },\r\n" + " \"summaryComments\": {\r\n" + " \"errors\": null,\r\n"
				+ " \"warnings\": null,\r\n" + " \"messages\": []\r\n" + " },\r\n" + " \"customOrderStatus\": {\r\n"
				+ " \"key\": null,\r\n" + " \"label\": null,\r\n" + " \"lastModifiedBy\": null,\r\n"
				+ " \"lastModifiedDate\": 0\r\n" + " },\r\n" + " \"customPaymentStatus\": {\r\n" + " \"key\": null,\r\n"
				+ " \"label\": null,\r\n" + " \"ctKey\": null,\r\n" + " \"lastModifiedBy\": null,\r\n"
				+ " \"lastModifiedDate\": 0\r\n" + " }\r\n" + " },\r\n" + "\"otherData\": null,\r\n"
				+ "\"data\": null,\r\n" + "\"freightChargeData\": null,\r\n" + "\"otherObjectData\": {\r\n"
				+ " \"salesforceOpportunityId\": \"0069D00000Q4sq0QAB\",\r\n" + " \"pdfToBeSent\":true\r\n" + "}\r\n"
				+ "}";
	}

	
}
